apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mauriciocarrion/mysqldb:latest
          ports:
            - containerPort: 3087
          env:
            - name: DB_PORT
              value: 3309
            - name: DB_HOST
              value: mysqldb
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "#@jj2802"
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
spec:
  selector:
    app: nodeapi
  ports:
    - port: 3087
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
spec:
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
        - name: nodeapi
          image: mauriciocarrion/nodeapi:latest
          ports:
            - containerPort: 3087
              targetPort: 3087
          env:
            - name: DB_PORT
              value: 3309
            - name: DB_HOST
              value: mysqldb
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "#@jj2802"

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
spec:
  selector:
    app: nodeapi
  ports:
    - port: 3087
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: web
          image: mauriciocarrion/kube-news:{{TAG}}
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_PASSWORD
              value: "pg#123"
            - name: DB_HOST
              value: "postgre"

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
