apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbcadjf
spec:
  selector:
    matchLabels:
      app: dbcadjf
  template:
    metadata:
      labels:
        app: dbcadjf
    spec:
      containers:
        - name: dbcadjf
          image: mauriciocarrion/dbcadjf:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "#@jj2802"
            - name: MYSQL_DATABASE
              value: "dbCad"
            - name: MYSQL_USER
              value: "jf.mysql"
            - name: MYSQL_PASSWORD
              value: "#@jj2802"
---
apiVersion: v1
kind: Service
metadata:
  name: dbcadjf
spec:
  selector:
    app: dbcadjf
  ports:
    - port: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicadjf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicadjf
  template:
    metadata:
      labels:
        app: apicadjf
    spec:
      containers:
        - name: apicadjf
          image: mauriciocarrion/apicadjf:latest
          ports:
            - containerPort: 3087
          env:
            - name: DB_PORT
              value: 3309
            - name: DB_HOST
              value: dbcadjf
            - name: DB_USER
              value: "jf.mysql"
            - name: DB_PASSWORD
              value: "#@jj2802"

---
apiVersion: v1
kind: Service
metadata:
  name: apicadjf
spec:
  selector:
    app: apicadjf
  ports:
    - port: 3087
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadjf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadjf
  template:
    metadata:
      labels:
        app: cadjf
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: cadjf
          image: mauriciocarrion/cadjf:latest
          ports:
            - containerPort: 80
          env:
            - name: API_HOST
              value: apicadjf
            - name: API_PORT
              value: 3387

---
apiVersion: v1
kind: Service
metadata:
  name: cadjf
spec:
  selector:
    app: cadjf
  ports:
    - port: 80
  type: LoadBalancer
